### ISSUE TITLE
qtwebkit-kiosk: logging

### ISSUE THREAD

**Issue by ghost** [opinsys/iivari#1]
Web-browser should write the following logging information to a local file:
- slides.json request status, successful/failed (screen_controller)
- All Javascript messages (warnings, errors, etc.)

**Comment by lamikae** [comment]
Javascript console messages are caught in Python callback and are written to log file.
See commits e2e8dee92072fadbe0ed09421b061cd8e2ff88b4 and f2b8b1e972ff688ac358834ea24c5044e43108e4
