### ISSUE TITLE
qtwebkit-kiosk: Application Cache updating

### ISSUE THREAD

**Issue by ghost** [opinsys/iivari#2]
If javascript, css or html files is changed (or new files) Application Cache and Manifest must be updated.

**Comment by lamikae** [comment]
This also requires a refresh signal. Dummy refresh implemented in window.displayCtrl, see 4dcbdbc4b7863f07dc70efb6ba706b13a2433f52

**Comment by lamikae** [comment]
Commit ce02e2428088bcc36094b413e1e5f6f535a7ed03 introduces a script that calculates a checksum into file "Manifest.revision" which is formulated from file contents in the app/ folder and static .css and .js files.

Include the provided post-commit script into .git/hooks (install script included) to calculate the checksum automatically after each commit.

**Comment by lamikae** [comment]
Rewritten to develop branch in 184f0b8d680d04b7d36ff68e73889f14b8d29a88
The manifest cache makes use of asset pipeline and its built-in digest feature.
