### ISSUE TITLE
Client: network connection status

### ISSUE THREAD

**Issue by ghost** [opinsys/iivari#3]
Displays should show an indicator when network connection to the server is broken and content cannot be updated. The indicator should be visible so that end-users responsible for updating content can determine easily if network is not working if the content doesn't update.

**Comment by lamikae** [comment]
Partial solution, based on window.navigator.onLine property, is in commit 768aace462df60356d0ecb4ad0f6fccd5d362093.

This does not work on Ubuntu 10.04 LTS, which ships with Qt 4.6. Would require Qt 4.7.

**Comment by lamikae** [comment]
Fixed in commit 3aff4a6b7331a6cc93f650c2f1ec7ce46888ce63.

**Comment by lamikae** [comment]
Backported to develop branch in 1a1a1110b9ed73146376baded560626ad23e2a12
